defaultVersion: "Version_2.0"
Version_2.0:
  version: "2.0"
  defaults:
    description: "Default parameters"
    start: 0
    size: 100
    connection:
      description: "URL of the NDEx server"
      host: "www.ndexbio.org"
      api: "/v2"
  replaceables:
    description: "Tabs used within urls to be replaced with content"
    uuid: "#UUID#"
    network: "#NETWORKID#"
    aspect: "#ASPECT#"
    start: "#START#"
    size: "#SIZE#"
    permission: "#PERMISSION#"
    key: "#KEY#"
    value: "#VALUE#"
    type: "#TYPE#"
  api:
    serverStatus:
      description: "Get Server Status"
      url: "/admin/status"
      method: "GET"
    user:
      authenticate:
        description: "Authenticate a User"
        url: "/user?valid=true"
        method: "GET"
    network:
      create:
        description: "Create a CX Network"
        url: "/network"
        method: "POST"
      update:
        description: "Update a Network"
        url: "/network/#NETWORKID#"
        method: "PUT"
      delete:
        description: "Delete a Network"
        url: "/network/#NETWORKID#"
        method: "DELETE"
      get:
        description: "Get Complete Network in CX format"
        url: "/network/#NETWORKID#"
        method: "GET"
      summary:
        get:
          description: "Get Network Summary"
          url: "/network/#NETWORKID#/summary"
          method: "GET"
      sample:
        set:
          description: "Get Network Summary"
          url: "/network/#NETWORKID#/sample"
          method: "PUT"
        get:
          description: "Set Network Sample"
          url: "/network/#NETWORKID#/sample"
          method: "GET"
      aspect:
        getMetaData:
          description: "Get Network CX Metadata Collection"
          url: "/network/#NETWORKID#/aspect"
          method: "GET"
        getMetaDataByName:
          description: "Get Network Aspect Metadata"
          url: "/network/#NETWORKID#/aspect/#ASPECT#/metadata"
          method: "GET"
        get:
          description: "Get a Network Aspect As CX"
          url: "/network/#NETWORKID#/aspect/#ASPECT#"
          method: "GET"
          params:
            size: "#SIZE#"
        update:
          description: "Update an Aspect of a Network"
          url: "/network/#NETWORKID#/aspect/#ASPECT#"
          method: "PUT"
      permission:
        get:
          description: "Get All Permissions on a Network"
          url: "/network/#NETWORKID#/permission"
          method: "GET"
          params:
            type: "#TYPE#"
            permission: "#PERMISSION#"
            start: "#START#"
            size: "#SIZE#"
        update:
          description: "Update Network Permission"
          url: "/network/#NETWORKID#/permission"
          method: "PUT"
          params:
            userid: "#UUID#"
            groupid: "#UUID#"
            permission: "#PERMISSION#"
        delete:
          description: "Delete Network Permission"
          url: "/network/#NETWORKID#/permission"
          method: "DELETE"
          params:
            userid: "#UUID#"
            groupid: "#UUID#"
      profile:
        update:
          description: "Update Network Profile"
          url: "/network/#NETWORKID#/profile"
          method: "PUT"
      systemproperties:
        set:
          description: "Set Network System Properties"
          url: "/network/#NETWORKID#/systemproperty"
          method: "PUT"
      properties:
        set:
          description: "Set Network Properties"
          url: "/network/#NETWORKID#/properties"
          method: "PUT"
      provenance:
        set:
          description: "Set Network Provenance"
          url: "/network/#NETWORKID#/provenance"
          method: "PUT"
        get:
          description: "Get Network Provenance"
          url: "/network/#NETWORKID#/provenance"
          method: "GET"
    search:
      user:
        description: "Search users"
        url: "/search/user"
        method: "POST"
        params:
          start: "#START#"
          size: "#SIZE#"
      group:
        description: "Search groups"
        url: "/search/group"
        method: "POST"
        params:
          start: "#START#"
          size: "#SIZE#"
      network:
        search:
          description: "Search network"
          url: "/search/network"
          method: "POST"
          params:
            start: "#START#"
            size: "#SIZE#"
        neighborhood:
          description: "Query Network As CX"
          url: "/search/network/#NETWORKID#/query"
          method: "POST"
          params:
            size: "#SIZE#"
Version_1.3:
  version: "1.3"
  defaults:
    description: "Default parameters"
    start: 0
    size: 100
    connection:
      description: "URL of the NDEx server"
      host: "www.ndexbio.org"
      api: "/rest"
  replaceables:
    description: "Tabs used within urls to be replaced with content"
    uuid: "#UUID#"
    network: "#NETWORKID#"
    aspect: "#ASPECT#"
    start: "#START#"
    size: "#SIZE#"
    permission: "#PERMISSION#"
    key: "#KEY#"
    value: "#VALUE#"
    type: "#TYPE#"
  api:
    serverStatus:
      description: "Get Server Status"
      url: "/admin/status"
      method: "GET"
    user:
      authenticate:
        description: "Authenticate a User"
        url: "/user/authenticate"
        method: "GET"
    network:
      create:
        description: "Create a CX Network"
        url: "/network/asCX"
        method: "POST"
      update:
        description: "Update a Network"
        url: "/network/asCX/#NETWORKID#"
        method: "PUT"
      delete:
        description: "Delete a Network"
        url: "/network/#NETWORKID#"
        method: "DELETE"
      get:
        description: "Get Complete Network in CX format"
        url: "/network/#NETWORKID#/asCX"
        method: "GET"
      summary:
        get:
          description: "Get Network Summary"
          url: "/network/#NETWORKID#/summary"
          method: "GET"
      aspect:
        getMetaData:
          description: "Get Network CX Metadata Collection"
          url: "/network/#NETWORKID#/metadata"
          method: "GET"
        get:
          description: "Get a Network Aspect As CX"
          url: "/network/#NETWORKID#/aspect/#ASPECT#/#SIZE#"
          method: "GET"
          params:
            size: "#SIZE#"
      permission:
        get:
          description: "Get All Permissions on a Network"
          url: "/network/#NETWORKID#/user/#PERMISSION#/#START#/#SIZE#"
          method: "GET"
          params:
            permission: "#PERMISSION#"
            start: "#START#"
            size: "#SIZE#"
        update:
          description: "Update Network Permission"
          url: "/network/#NETWORKID#/member"
          method: "PUT"
          params:
            userid: "#UUID#"
            groupid: "#UUID#"
            permission: "#PERMISSION#"
        delete:
          description: "Delete Network Permission"
          url: "/network/#NETWORKID#/member/#UUID#"
          method: "DELETE"
          params:
            userid: "#UUID#"
            groupid: "#UUID#"
      systemproperties:
        set:
          description: "Set Network System Properties"
          url: "/network/#NETWORKID#/setFlag/#KEY#=#VALUE#"
          method: "PUT"
      properties:
        set:
          description: "Set Network Properties"
          url: "/network/#NETWORKID#/properties"
          method: "PUT"
      provenance:
        set:
          description: "Set Network Provenance"
          url: "/network/#NETWORKID#/provenance"
          method: "PUT"
        get:
          description: "Get Network Provenance"
          url: "/network/#NETWORKID#/provenance"
          method: "GET"
    search:
      user:
        description: "Search users"
        url: "/user/search/#START#/#SIZE#"
        method: "POST"
        params:
          start: "#START#"
          size: "#SIZE#"
      group:
        description: "Search groups"
        url: "/group/search/#START#/#SIZE#"
        method: "POST"
        params:
          start: "#START#"
          size: "#SIZE#"
      network:
        search:
          description: "Search network"
          url: "/network/textsearch/#START#/#SIZE#"
          method: "POST"
          params:
            start: "#START#"
            size: "#SIZE#"
        neighborhood:
          description: "Query Network As CX"
          url: "/network/#NETWORKID#/asCX/query"
          method: "POST"
          params:
            size: "#SIZE#"
